In [18]:
import tensorflow as tf

In [19]:
import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4], [3, 4], [3, 4]])
y = np.array([0, 0, 0,0, 1, 1, 1,1])
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.5, random_state=45423,)
sss.get_n_splits(X, y)
print(sss)
for train_index, test_index in sss.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
print("X_train \n"+str(X_train))
print( "X_test \n" +str(X_test))
print("y_train \n"+str(y_train))
print( "y_test \n" +str(y_test))

StratifiedShuffleSplit(n_splits=1, random_state=45423, test_size=0.5,
            train_size=None)
TRAIN: [3 0 5 7] TEST: [1 4 2 6]
X_train 
[[3 4]
 [1 2]
 [3 4]
 [3 4]]
X_test 
[[3 4]
 [1 2]
 [1 2]
 [3 4]]
y_train 
[0 0 1 1]
y_test 
[0 1 0 1]


In [20]:
RA50_Data="/mnt/0A60B2CB60B2BD2F/Projects/flow_regime_recognition_CameraPosition/datasets_preprocessed/RightAngled50/2022-11-08 17:34:40.437549/tf_dataset_test.tf"
path_tf_dataset_test=RA50_Data
tf_dataset_test = tf.data.experimental.load(path_tf_dataset_test)

In [21]:
sss.split(tf_dataset_test)

<_LoadDataset element_spec=(TensorSpec(shape=(None, 56, 56, 1), dtype=tf.float32, name=None), TensorSpec(shape=(None, 4), dtype=tf.float32, name=None))>